<?php get_header();
$portrait_id = absint(get_theme_mod('hero_portrait'));
$portrait = $portrait_id ? wp_get_attachment_image_url($portrait_id, 'large') : smp_asset('profile/shakeel-mureed-portrait.png');
$skills = ['Magento 2','Hyvä','PHP','MySQL','Alpine.js','Tailwind CSS','REST APIs','WordPress','WooCommerce','Linux','Git','Jira'];
?>
<main id="home">
<section class="hero"><div class="container hero-grid"><div class="hero-copy reveal">
  <p class="eyebrow"><?php echo esc_html(smp_mod('hero_eyebrow')); ?></p><h1><?php $title=esc_html(smp_mod('hero_title'));$highlight=esc_html(smp_mod('hero_highlight'));echo $highlight ? str_replace($highlight,'<span>'.$highlight.'</span>',$title) : $title; ?></h1>
  <p class="lead"><?php echo esc_html(smp_mod('hero_lead')); ?></p>
  <div class="actions"><a class="button" href="#portfolio"><?php echo esc_html(smp_mod('hero_primary_label')); ?></a><a class="button button-secondary" href="#resumes"><?php echo esc_html(smp_mod('hero_secondary_label')); ?></a></div>
  <div class="proof"><span><strong><?php echo esc_html(smp_mod('proof_one')); ?></strong></span><span><strong><?php echo esc_html(smp_mod('proof_two')); ?></strong></span><span><strong><?php echo esc_html(smp_mod('proof_three')); ?></strong></span></div>
</div><div class="hero-visual reveal"><div class="portrait-frame"><img class="hero-portrait" src="<?php echo esc_url($portrait); ?>" alt="Shakeel Mureed"><div class="portrait-caption"><small>Senior Magento 2 &amp; E-commerce Developer</small><strong>Shakeel Mureed</strong></div></div><div class="tech-badge"><span>Magento 2</span><span>Hyvä</span><span>WordPress</span></div><div class="floating-note note-one"><small>Experience</small><strong>8+ years Magento 2</strong></div><div class="floating-note note-two"><small>Location</small><strong>Lahore · Remote</strong></div></div></div></section>

<section id="about" class="section"><div class="container split"><div class="section-intro reveal"><p class="eyebrow">About</p><h2><?php echo esc_html(smp_mod('about_heading')); ?></h2></div><div class="about-copy reveal"><p class="lead"><?php echo esc_html(smp_mod('about_lead')); ?></p><?php echo wp_kses_post(wpautop(smp_mod('about_body'))); ?><a class="text-link" href="#experience">Explore my experience <span>→</span></a></div></div></section>

<section id="services" class="section section-muted"><div class="container"><div class="section-heading reveal"><div><p class="eyebrow">Services</p><h2><?php echo esc_html(smp_mod('services_heading')); ?></h2></div><p><?php echo esc_html(smp_mod('services_intro')); ?></p></div><div class="service-grid">
<?php $q=smp_items('smp_service'); $n=1; while($q->have_posts()):$q->the_post(); $bullets=array_filter(array_map('trim',explode("\n",get_post_meta(get_the_ID(),'_smp_bullets',true)))); ?>
<article class="service-card reveal"><span><?php echo esc_html(sprintf('%02d',$n++)); ?></span><h3><?php the_title(); ?></h3><div><?php the_content(); ?></div><?php if($bullets): ?><ul><?php foreach($bullets as $b) echo '<li>'.esc_html($b).'</li>'; ?></ul><?php endif; ?></article>
<?php endwhile; wp_reset_postdata(); ?></div></div></section>

<section id="portfolio" class="section portfolio-section"><div class="container"><div class="section-heading reveal"><div><p class="eyebrow">Selected Work</p><h2><?php echo esc_html(smp_mod('portfolio_heading')); ?></h2></div><p><?php echo esc_html(smp_mod('portfolio_intro')); ?></p></div>
<div class="filter-row reveal"><button class="filter is-active" data-filter="all" aria-pressed="true">All</button><button class="filter" data-filter="magento-2" aria-pressed="false">Magento 2</button><button class="filter" data-filter="hyva" aria-pressed="false">Hyvä</button><button class="filter" data-filter="wordpress" aria-pressed="false">WordPress</button><button class="filter" data-filter="woocommerce" aria-pressed="false">WooCommerce</button></div><div class="project-grid">
<?php $q=smp_items('smp_project'); while($q->have_posts()):$q->the_post(); $id=get_the_ID(); $tags=array_filter(array_map('trim',explode(',',get_post_meta($id,'_smp_tags',true)))); $cats=strtolower(implode(' ',array_map(fn($x)=>sanitize_title($x),$tags))); $site=get_post_meta($id,'_smp_website',true); $asset=get_post_meta($id,'_smp_asset',true); $img=get_the_post_thumbnail_url($id,'large') ?: smp_asset($asset); ?>
<article class="project-card reveal" data-category="<?php echo esc_attr($cats); ?>"><img class="project-image" src="<?php echo esc_url($img); ?>" alt="<?php echo esc_attr(get_the_title()); ?>"><div class="project-content"><div class="tags"><?php foreach($tags as $tag) echo '<span>'.esc_html($tag).'</span>'; ?></div><h3><?php the_title(); ?></h3><p><?php echo esc_html(get_the_excerpt()); ?></p><div class="project-actions"><button class="text-link project-modal-open" type="button">View complete case study <span>→</span></button><?php if($site): ?><a class="site-link" href="<?php echo esc_url($site); ?>" target="_blank" rel="noopener">Visit website ↗</a><?php else: ?><span class="site-link site-link-muted">Private project</span><?php endif; ?></div><template class="project-template"><div class="modal-data" data-title="<?php echo esc_attr(get_the_title()); ?>" data-image="<?php echo esc_url($img); ?>" data-url="<?php echo esc_url($site); ?>" data-platform="<?php echo esc_attr(implode(' · ',$tags)); ?>"><?php echo wp_kses_post(apply_filters('the_content',get_the_content())); ?></div></template></div></article>
<?php endwhile; wp_reset_postdata(); ?></div></div></section>

<section id="julefabrikken" class="section module-section"><div class="container"><div class="section-heading reveal"><div><p class="eyebrow">Featured Magento Engineering</p><h2><?php echo esc_html(smp_mod('modules_heading')); ?></h2></div><p><?php echo esc_html(smp_mod('modules_intro')); ?></p></div><div class="module-grid">
<?php $q=smp_items('smp_module'); while($q->have_posts()):$q->the_post(); $id=get_the_ID(); $bullets=array_filter(array_map('trim',explode("\n",get_post_meta($id,'_smp_bullets',true)))); ?><article class="module-card reveal"><span class="module-status delivered">Delivered</span><p class="module-name"><?php echo esc_html(get_post_meta($id,'_smp_subtitle',true)); ?></p><h3><?php the_title(); ?></h3><?php the_content(); ?><ul><?php foreach($bullets as $b) echo '<li>'.esc_html($b).'</li>'; ?></ul></article><?php endwhile;wp_reset_postdata(); ?></div></div></section>

<section id="experience" class="section section-dark"><div class="container experience-grid"><div class="reveal"><p class="eyebrow">Experience</p><h2><?php echo esc_html(smp_mod('experience_heading')); ?></h2><p class="lead"><?php echo esc_html(smp_mod('experience_intro')); ?></p><div class="skill-cloud"><?php foreach($skills as $s) echo '<span>'.esc_html($s).'</span>'; ?></div></div><div class="timeline reveal">
<?php $q=smp_items('smp_experience');while($q->have_posts()):$q->the_post();$id=get_the_ID();?><article><span><?php echo esc_html(get_post_meta($id,'_smp_period',true)); ?></span><div><h3><?php the_title(); ?></h3><?php the_content(); ?><small><?php echo esc_html(get_post_meta($id,'_smp_subtitle',true)); ?></small></div></article><?php endwhile;wp_reset_postdata();?></div></div></section>

<section id="resumes" class="section resume-section"><div class="container"><div class="section-heading reveal"><div><p class="eyebrow">Resume Downloads</p><h2>Choose the resume that matches the opportunity.</h2></div><p>Each PDF is tailored to a specific role while keeping the same employment history and contact information.</p></div><div class="resume-grid">
<?php $resumes=[['Magento 2 Resume','Best for Magento backend, full-stack, Hyvä and Adobe Commerce-focused roles.','Shakeel_Mureed_Magento_Resume.pdf'],['WordPress Resume','Best for WordPress, WooCommerce, custom theme and plugin roles.','Shakeel_Mureed_WordPress_Resume.pdf'],['General E-commerce Resume','Balanced profile for senior e-commerce and full-stack web opportunities.','Shakeel_Mureed_General_Resume.pdf']];foreach($resumes as $i=>$r):?><article class="resume-card reveal"><span><?php echo esc_html(sprintf('%02d',$i+1));?></span><h3><?php echo esc_html($r[0]);?></h3><p><?php echo esc_html($r[1]);?></p><a class="button" href="<?php echo smp_asset('resumes/'.$r[2]);?>" download>Download PDF</a></article><?php endforeach;?></div></div></section>

<section id="contact" class="section contact-section"><div class="container contact-grid reveal"><div><p class="eyebrow">Contact</p><h2><?php echo esc_html(smp_mod('contact_heading'));?></h2><p class="lead"><?php echo esc_html(smp_mod('contact_intro'));?></p><div class="contact-links"><a href="mailto:<?php echo antispambot(esc_attr(smp_mod('contact_email')));?>"><?php echo antispambot(esc_html(smp_mod('contact_email')));?></a><a href="tel:<?php echo esc_attr(preg_replace('/[^+0-9]/','',smp_mod('contact_phone')));?>"><?php echo esc_html(smp_mod('contact_phone'));?></a><a href="<?php echo esc_url(smp_mod('linkedin_url'));?>" target="_blank" rel="noopener">LinkedIn profile</a><span><?php echo esc_html(smp_mod('contact_location'));?></span></div></div>
<form id="contact-form"><input type="hidden" name="action" value="smp_contact"><label>Name<input name="name" required></label><label>Email<input type="email" name="email" required></label><label>Project type<select name="project"><option>Magento 2 Development</option><option>Hyvä Theme Work</option><option>Magento Bug or Performance Issue</option><option>WordPress / WooCommerce</option><option>Remote Role / Contract Opportunity</option></select></label><label>Project details<textarea name="message" required></textarea></label><label class="smp-hp" aria-hidden="true">Website<input name="website" tabindex="-1" autocomplete="off"></label><button class="button" type="submit">Send Project Details</button><p id="form-status" class="form-status" role="status"></p></form></div></section>
</main>
<dialog id="project-modal" class="project-modal"><div class="project-modal-panel"><button class="modal-close" type="button" data-modal-close aria-label="Close">×</button><div class="modal-project-media"><img data-modal-image alt=""></div><div class="modal-project-header"><div><p class="eyebrow" data-modal-platform></p><h2 data-modal-title></h2></div><a class="button button-small" data-modal-url target="_blank" rel="noopener">Visit website ↗</a></div><div class="markdown-content" data-modal-content></div></div></dialog>
<?php get_footer(); ?>
